# -*- coding: utf-8 -*-
"""ICEYE Toolbox plugin initialization.

/***************************************************************************
 ICEYE Toolbox
                                 A QGIS plugin
 ICEYE Toolbox
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-23
        copyright            : (C) 2025 by Santeri Kuronen
        email                : santeri.kuronen@iceye.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ICEYE Toolbox plugin class.

    Parameters
    ----------
    iface : QgsInterface
        QGIS interface instance.

    Returns
    -------
    IceyeToolbox
        Plugin instance.
    """
    #
    from .iceye_toolbox import IceyeToolbox

    return IceyeToolbox(iface)
