# -*- coding: utf-8 -*-
"""ICEYE Toolbox plugin for QGIS.

/***************************************************************************
 ICEYE Toolbox
                                 A QGIS plugin
 ICEYE Toolbox
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Santeri Kuronen
        email                : santeri.kuronen@iceye.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from pathlib import Path

from qgis.PyQt.QtCore import QCoreApplication, QSettings, Qt, QTimer, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QToolBar

from .core.auto_styler import AutoStyler
from .core.autofocus import AutofocusTool
from .core.color import ColorTool
from .core.cropper import CropTool
from .core.export import ExportTool
from .core.metadata import MetadataProvider
from .core.video import VideoTool
from .gui.batch_tool import BatchToolbarAction
from .gui.canvas_rotation_tool import MandalaToolbarAction
from .gui.crop_toolbar import CropToolbarAction
from .gui.lens_tool import LensToolbarAction
from .gui.measuring_tool import MeasuringToolbarAction
from .gui.metadata_widget import MetadataWidget
from .gui.stac_catalog_widget import StacCatalogWidget
from .gui.toolbar_button_policy import ToolbarButtonPolicy

# Initialize Qt resources from file resources.py
from .resources.resources import *


class ICEYEToolbox:
    """QGIS Plugin Implementation."""

    def __init__(self, iface) -> None:
        """Initialize the plugin with QGIS interface.

        Parameters
        ----------
        iface : QgsInterface
            Interface providing hooks to manipulate QGIS at runtime.
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = Path(__file__).resolve().parent

        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = self.plugin_dir / "i18n" / f"ICEYEToolbox_{locale}.qm"

        if locale_path.exists():
            self.translator = QTranslator()
            self.translator.load(str(locale_path))
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&ICEYE Toolbox")

        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar("ICEYE Toolbox")
        self.toolbar.setObjectName("ICEYE Toolbox")

        # print "** INITIALIZING ICEYE Toolbox"
        self.pluginIsActive = False

        self.temp_files = []

        self.metadata_provider = MetadataProvider()
        self.toolbar_button_policy = ToolbarButtonPolicy(
            self.iface, metadata_provider=self.metadata_provider
        )

        self.cropper = CropTool(self.iface)

        self.video_tool = VideoTool(self.iface, self.metadata_provider, self.temp_files)

        self.color_tool = ColorTool(self.iface, self.metadata_provider)

        self.target_focus_tool = AutofocusTool(self.iface, self.metadata_provider)

        self.export_tool = ExportTool(self.iface)

        self.metadata_widget = MetadataWidget(
            metadata_provider=self.metadata_provider,
            parent=self.iface.mainWindow(),
        )
        self.stac_catalog_widget = StacCatalogWidget(parent=self.iface.mainWindow())
        self.stac_catalog_action = None
        self.export_layer_action = None
        self.mandala_toolbar_action = MandalaToolbarAction(
            self.iface,
            metadata_provider=self.metadata_provider,
            toolbar_button_policy=self.toolbar_button_policy,
        )
        self.auto_styler = AutoStyler(self.iface, self.metadata_provider)
        self.lens_toolbar_action = LensToolbarAction(
            self.iface,
            metadata_provider=self.metadata_provider,
            toolbar_button_policy=self.toolbar_button_policy,
        )
        self.crop_toolbar_action = CropToolbarAction(
            self.iface,
            crop_tool=self.cropper,
            target_focus_tool=self.target_focus_tool,
            video_tool=self.video_tool,
            color_tool=self.color_tool,
            lens_toolbar_action=self.lens_toolbar_action,
            toolbar_button_policy=self.toolbar_button_policy,
        )

        self.lens_toolbar_action._crop_toolbar_action = self.crop_toolbar_action

        self.batch_toolbar_action = BatchToolbarAction(
            self.iface,
            metadata_provider=self.metadata_provider,
            crop_tool=self.cropper,
            target_focus_tool=self.target_focus_tool,
            color_tool=self.color_tool,
            video_tool=self.video_tool,
        )

        self.measuring_toolbar_action = MeasuringToolbarAction(
            self.iface,
            metadata_provider=self.metadata_provider,
            toolbar_button_policy=self.toolbar_button_policy,
        )

    # noinspection PyMethodMayBeStatic
    def tr(self, message: str) -> str:
        """Get the translation for a string using Qt translation API."""
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("ICEYE Toolbox", message)

    def add_action(
        self,
        icon_path: str,
        text: str,
        callback,
        enabled_flag: bool = True,
        add_to_menu: bool = True,
        add_to_toolbar: bool = True,
        status_tip: str | None = None,
        whats_this: str | None = None,
        parent=None,
    ) -> QAction:
        """Add a toolbar icon and optional menu entry.

        Parameters
        ----------
        icon_path : str
            Path to icon (resource or filesystem).
        text : str
            Text for menu and tooltip.
        callback : callable
            Called when action is triggered.
        enabled_flag : bool, optional
            Whether action is enabled. Default is True.
        add_to_menu : bool, optional
            Add to plugin menu. Default is True.
        add_to_toolbar : bool, optional
            Add to toolbar. Default is True.
        status_tip : str or None, optional
            Status bar text on hover.
        whats_this : str or None, optional
            Help text on hover.
        parent : QWidget or None, optional
            Parent widget.

        Returns
        -------
        QAction
            Created action (also appended to self.actions).
        """
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self) -> None:
        """Create menu entries and toolbar icons in the QGIS GUI."""
        self.mandala_toolbar_action.setup()
        self.lens_toolbar_action.setup()
        self.crop_toolbar_action.setup()
        self.measuring_toolbar_action.setup()
        self.batch_toolbar_action.setup()
        self.stac_catalog_action = self.add_action(
            icon_path=":/plugins/ICEYEToolbox/catalog-svgrepo-com.svg",
            text=self.tr("Toggle STAC Catalog"),
            callback=self.toggle_stac_catalog_widget,
            parent=self.iface.mainWindow(),
            status_tip="Show or hide STAC catalog",
        )
        self.stac_catalog_action.setCheckable(True)
        self.stac_catalog_action.setChecked(True)
        self.stac_catalog_widget.visibilityChanged.connect(
            self._on_stac_visibility_changed
        )

        exclusive_tools = [
            self.crop_toolbar_action.map_tool,
            self.lens_toolbar_action.lens_tool,
            self.batch_toolbar_action.map_tool,
        ]
        for toolbar_action in [
            self.mandala_toolbar_action,
            self.measuring_toolbar_action,
        ]:
            toolbar_action.register_exclusive_tools(exclusive_tools)

        self.toolbar_button_policy.setup()

        # # Export actions
        self.export_layer_action = self.add_action(
            icon_path=":/plugins/ICEYEToolbox/export-svgrepo-com.svg",
            text=self.tr("Export Layer"),
            callback=lambda: self.export_tool.export_layer(
                layer=self.iface.activeLayer()
            ),
            parent=self.iface.mainWindow(),
            status_tip="Export the current layer",
        )
        self.toolbar_button_policy.register(
            self.export_layer_action,
            self.toolbar_button_policy.enabled_if_iceye_layer,
        )
        self.toolbar_button_policy.refresh()

        self.add_action(
            icon_path=":/plugins/ICEYEToolbox/screenshot-svgrepo-com.svg",
            text=self.tr("Screenshot canvas"),
            callback=lambda: self.export_tool.export_canvas(
                iface=self.iface, canvas=self.iface.mapCanvas()
            ),
            parent=self.iface.mainWindow(),
            status_tip="Export the current canvas",
        )

        self.run()

    # --------------------------------------------------------------------------

    def onClosePlugin(self) -> None:
        """Clean up when plugin dock widget is closed."""
        # print "** CLOSING ICEYE Tool Box"

        # disconnects
        self.dockwidget.closing_plugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        self.dockwidget = None
        self.crop_dockwidget = None
        self.metadata_widget = None
        self.target_focus_tool = None
        self.mandala_toolbar_action = None
        self.crop_toolbar_action = None
        self.auto_styler = None
        self.pluginIsActive = False

    def unload(self) -> None:
        """Remove the plugin menu item and icon from QGIS GUI."""
        if self.metadata_widget:
            self.iface.removeDockWidget(self.metadata_widget)
            self.metadata_widget.deleteLater()
            self.metadata_widget = None

        if self.stac_catalog_widget:
            self.iface.removeDockWidget(self.stac_catalog_widget)
            self.stac_catalog_widget.deleteLater()
            self.stac_catalog_widget = None

        for action in self.actions:
            try:
                self.iface.removePluginMenu(self.tr("&ICEYE Toolbox"), action)
                self.iface.removeToolBarIcon(action)
            except Exception:
                pass

        self.toolbar_button_policy.unload()
        self.mandala_toolbar_action.unload()
        self.lens_toolbar_action.unload()
        self.crop_toolbar_action.unload()
        self.batch_toolbar_action.unload()
        self.measuring_toolbar_action.unload()
        # Delete toolbar - this automatically cleans up all widgets
        if hasattr(self, "toolbar"):
            try:
                del self.toolbar
            except Exception:
                pass
        for temp_file in self.temp_files:
            try:
                temp_path = Path(temp_file)
                if temp_path.exists():
                    temp_path.unlink()
                    print(f"Cleaned up temporary file: {temp_file}")
            except Exception as e:
                print(f"Failed to remove temp file {temp_file}: {e}")

    # --------------------------------------------------------------------------

    def get_dockwidget(self):
        """Return the dock widget instance."""
        return self.dockwidget

    def update_ui_label(self, text: str) -> None:
        """Update the label text."""
        if self.dockwidget:
            self.dockwidget.label.setText(text)

    def get_selected_option(self) -> str | None:
        """Get the currently selected combo box option."""
        if self.dockwidget:
            return self.dockwidget.comboBox.currentText()
        return None

    def run(self) -> None:
        """Load and start the plugin (add dock widgets)."""
        # Metadata widget
        self.iface.addDockWidget(Qt.RightDockWidgetArea, self.metadata_widget)
        self.metadata_widget.show()
        self.metadata_widget.closeEvent = self.onClosePlugin

        # STAC catalog widget
        self.iface.addDockWidget(Qt.RightDockWidgetArea, self.stac_catalog_widget)
        if self.stac_catalog_action and self.stac_catalog_action.isChecked():
            self.stac_catalog_widget.show()
        else:
            self.stac_catalog_widget.hide()

    def toggle_stac_catalog_widget(self, checked: bool = True) -> None:
        """Show or hide the STAC catalog dock widget."""
        if not self.stac_catalog_widget:
            return
        if checked:
            self.stac_catalog_widget.show()
            self.stac_catalog_widget.raise_()
        else:
            self.stac_catalog_widget.hide()

    def _on_stac_visibility_changed(self, visible: bool) -> None:
        if not self.stac_catalog_action:
            return
        self.stac_catalog_action.blockSignals(True)
        self.stac_catalog_action.setChecked(visible)
        self.stac_catalog_action.blockSignals(False)
